version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.23
    container_name: mysql
    command: --init-file /init-backend.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=e-commerce
      - MYSQL_USER=anniemon
      - MYSQL_PASSWORD=anniemon
      - MYSQL_TCP_PORT=3307
      - LANG=C.UTF-8
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init-backend.sql:/init-backend.sql
    ports:
      - '3307:3307'
  redis:
    image: redis:4-alpine
    container_name: redis
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_PORT=3307
      - DB_USERNAME=anniemon
      - DB_PASSWORD=anniemon
      - DB_DATABASE=e-commerce
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql
