version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.23
    container_name: mysql
    command: --init-file /init-backend.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=e_commerce_local
      - MYSQL_USER=anniemon
      - MYSQL_PASSWORD=anniemon
      - MYSQL_TCP_PORT=3307
      - LANG=C.UTF-8
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init-backend.sql:/init-backend.sql
    ports:
      - '3307:3307'
  redis:
    image: redis:4-alpine
    container_name: redis
    ports:
      - '6379:6379'
