# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        workspace: ['test:unit', 'test:e2e']

    services:
      mysql:
        image: mysql:8.0.23
        ports:
          - 3307:3306
        env:
          MYSQL_DATABASE: e_commerce_test
          MYSQL_ROOT_PASSWORD: root

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: init database
        run: |
          sudo /etc/init.d/mysql start
          mysql -h 127.0.0.1 -P 3307 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS e_commerce_test;"
          mysql -h 127.0.0.1 -P 3307 -uroot -proot e_commerce_test < ./docker/mysql/init-backend.sql
      - name: npm run ${{ matrix.workspace }}
        run: npm run ${{ matrix.workspace }}
